name: flutter_code_base
description: The Flutter Project Base Created by BrianNguyen
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  #------------------
  #Cores
  get_it: ^7.2.0
  flutter_bloc: ^7.0.1
  equatable: ^2.0.3
  logger: ^1.0.0
   # flutter pub run build_runner build --delete-conflicting-outputs
  json_annotation: ^4.1.0
  retrofit: ^2.0.1
  # flutter packages pub run build_runner build
  floor: ^1.1.0
  flutter_secure_storage: ^4.2.0
  flutter_easyloading: ^3.0.0
  #------------------
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^2.0.0+3
  json_serializable: ^4.1.3
  floor_generator: ^1.1.0
  build_runner: ^2.0.5
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

assets:
    - assets/images/
    - assets/icons/